### ISSUE TITLE
XUnit tests

### ISSUE THREAD

**Issue by NicoCG** [peacecwz/azure-storage-cli#2]
Hi @peacecwz,

Please could you add `xunit` tests to this project.

**Comment by peacecwz** [comment]
Yeah I would like to follow way with TDD. I will write unit and integration tests and follow as TDD

**Comment by NicoCG** [comment]
@peacecwz do you have date on when this will be implemented?

**Comment by peacecwz** [comment]
Okey I'm starting @NicoCG covering tests

**Comment by NicoCG** [comment]
Cool
